/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TripDetailRouteImport } from './routes/trip-detail'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminItinerariesRouteImport } from './routes/admin.itineraries'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMeetupsRouteImport } from './routes/admin.meetups'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as ApiBookingRouteImport } from './routes/api/booking'
import { Route as ApiEnquiriesRouteImport } from './routes/api/enquiries'
import { Route as ApiItinerarySubmissionsRouteImport } from './routes/api/itinerary-submissions'
import { Route as ApiMeetupsRouteImport } from './routes/api/meetups'
import { Route as ApiMyBookingsRouteImport } from './routes/api/my-bookings'
import { Route as ApiTripsRouteImport } from './routes/api/trips'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as ItinerarySubmitRouteImport } from './routes/itinerary.submit'
import { Route as AdminMeetupsIndexRouteImport } from './routes/admin.meetups.index'
import { Route as AdminTripsIndexRouteImport } from './routes/admin.trips.index'
import { Route as AdminTripsNewRouteImport } from './routes/admin.trips.new'
import { Route as ApiAdminBookingsRouteImport } from './routes/api/admin/bookings'
import { Route as ApiAdminEnquiriesRouteImport } from './routes/api/admin/enquiries'
import { Route as ApiAdminItinerarySubmissionSettingsRouteImport } from './routes/api/admin/itinerary-submission-settings'
import { Route as ApiAdminItinerarySubmissionsRouteImport } from './routes/api/admin/itinerary-submissions'
import { Route as ApiAdminMeetupsRouteImport } from './routes/api/admin/meetups'
import { Route as ApiAdminTripsRouteImport } from './routes/api/admin/trips'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiTripsTripIdRouteImport } from './routes/api/trips/$tripId'
import { Route as AdminTripsTripIdEditRouteImport } from './routes/admin.trips.$tripId.edit'
import { Route as ApiAdminBookingsBookingIdRouteImport } from './routes/api/admin/bookings/$bookingId'
import { Route as ApiAdminEnquiresEnquiryIdRouteImport } from './routes/api/admin/enquires/$enquiryId'
import { Route as ApiAdminItinerarySubmissionsSubmissionIdRouteImport } from './routes/api/admin/itinerary-submissions.$submissionId'
import { Route as ApiAdminMeetupsMeetupIdRouteImport } from './routes/api/admin/meetups.$meetupId'
import { Route as ApiAdminMeetupsImagesRouteImport } from './routes/api/admin/meetups.images'
import { Route as ApiAdminTripsTripIdRouteImport } from './routes/api/admin/trips/$tripId'
import { Route as ApiTripsTripIdImagesRouteImport } from './routes/api/trips/$tripId.images'
import { Route as ApiTripsTripIdItineraryRouteImport } from './routes/api/trips/$tripId.itinerary'
import { Route as ApiTripsTripIdImagesImageIdRouteImport } from './routes/api/trips/$tripId.images.$imageId'
import { Route as ApiTripsTripIdItineraryItineraryIdRouteImport } from './routes/api/trips/$tripId.itinerary.$itineraryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TripDetailRoute = TripDetailRouteImport.update({
  id: '/trip-detail',
  path: '/trip-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItinerariesRoute = AdminItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMeetupsRoute = AdminMeetupsRouteImport.update({
  id: '/meetups',
  path: '/meetups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const ApiBookingRoute = ApiBookingRouteImport.update({
  id: '/api/booking',
  path: '/api/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnquiriesRoute = ApiEnquiriesRouteImport.update({
  id: '/api/enquiries',
  path: '/api/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItinerarySubmissionsRoute = ApiItinerarySubmissionsRouteImport.update({
  id: '/api/itinerary-submissions',
  path: '/api/itinerary-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetupsRoute = ApiMeetupsRouteImport.update({
  id: '/api/meetups',
  path: '/api/meetups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyBookingsRoute = ApiMyBookingsRouteImport.update({
  id: '/api/my-bookings',
  path: '/api/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripsRoute = ApiTripsRouteImport.update({
  id: '/api/trips',
  path: '/api/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/dashboard/bookings',
  path: '/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerarySubmitRoute = ItinerarySubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ItineraryRoute,
} as any)
const AdminMeetupsIndexRoute = AdminMeetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMeetupsRoute,
} as any)
const AdminTripsIndexRoute = AdminTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTripsRoute,
} as any)
const AdminTripsNewRoute = AdminTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTripsRoute,
} as any)
const ApiAdminBookingsRoute = ApiAdminBookingsRouteImport.update({
  id: '/api/admin/bookings',
  path: '/api/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEnquiriesRoute = ApiAdminEnquiriesRouteImport.update({
  id: '/api/admin/enquiries',
  path: '/api/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminItinerarySubmissionSettingsRoute =
  ApiAdminItinerarySubmissionSettingsRouteImport.update({
    id: '/api/admin/itinerary-submission-settings',
    path: '/api/admin/itinerary-submission-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminItinerarySubmissionsRoute =
  ApiAdminItinerarySubmissionsRouteImport.update({
    id: '/api/admin/itinerary-submissions',
    path: '/api/admin/itinerary-submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminMeetupsRoute = ApiAdminMeetupsRouteImport.update({
  id: '/api/admin/meetups',
  path: '/api/admin/meetups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTripsRoute = ApiAdminTripsRouteImport.update({
  id: '/api/admin/trips',
  path: '/api/admin/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripsTripIdRoute = ApiTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => ApiTripsRoute,
} as any)
const AdminTripsTripIdEditRoute = AdminTripsTripIdEditRouteImport.update({
  id: '/$tripId/edit',
  path: '/$tripId/edit',
  getParentRoute: () => AdminTripsRoute,
} as any)
const ApiAdminBookingsBookingIdRoute =
  ApiAdminBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => ApiAdminBookingsRoute,
  } as any)
const ApiAdminEnquiresEnquiryIdRoute =
  ApiAdminEnquiresEnquiryIdRouteImport.update({
    id: '/api/admin/enquires/$enquiryId',
    path: '/api/admin/enquires/$enquiryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminItinerarySubmissionsSubmissionIdRoute =
  ApiAdminItinerarySubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => ApiAdminItinerarySubmissionsRoute,
  } as any)
const ApiAdminMeetupsMeetupIdRoute = ApiAdminMeetupsMeetupIdRouteImport.update({
  id: '/$meetupId',
  path: '/$meetupId',
  getParentRoute: () => ApiAdminMeetupsRoute,
} as any)
const ApiAdminMeetupsImagesRoute = ApiAdminMeetupsImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => ApiAdminMeetupsRoute,
} as any)
const ApiAdminTripsTripIdRoute = ApiAdminTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => ApiAdminTripsRoute,
} as any)
const ApiTripsTripIdImagesRoute = ApiTripsTripIdImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => ApiTripsTripIdRoute,
} as any)
const ApiTripsTripIdItineraryRoute = ApiTripsTripIdItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => ApiTripsTripIdRoute,
} as any)
const ApiTripsTripIdImagesImageIdRoute =
  ApiTripsTripIdImagesImageIdRouteImport.update({
    id: '/$imageId',
    path: '/$imageId',
    getParentRoute: () => ApiTripsTripIdImagesRoute,
  } as any)
const ApiTripsTripIdItineraryItineraryIdRoute =
  ApiTripsTripIdItineraryItineraryIdRouteImport.update({
    id: '/$itineraryId',
    path: '/$itineraryId',
    getParentRoute: () => ApiTripsTripIdItineraryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/itinerary': typeof ItineraryRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trip-detail': typeof TripDetailRoute
  '/trips': typeof TripsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/itineraries': typeof AdminItinerariesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meetups': typeof AdminMeetupsRouteWithChildren
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/api/booking': typeof ApiBookingRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/api/itinerary-submissions': typeof ApiItinerarySubmissionsRoute
  '/api/meetups': typeof ApiMeetupsRoute
  '/api/my-bookings': typeof ApiMyBookingsRoute
  '/api/trips': typeof ApiTripsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/itinerary/submit': typeof ItinerarySubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRouteWithChildren
  '/api/admin/enquiries': typeof ApiAdminEnquiriesRoute
  '/api/admin/itinerary-submission-settings': typeof ApiAdminItinerarySubmissionSettingsRoute
  '/api/admin/itinerary-submissions': typeof ApiAdminItinerarySubmissionsRouteWithChildren
  '/api/admin/meetups': typeof ApiAdminMeetupsRouteWithChildren
  '/api/admin/trips': typeof ApiAdminTripsRouteWithChildren
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/trips/$tripId': typeof ApiTripsTripIdRouteWithChildren
  '/admin/meetups/': typeof AdminMeetupsIndexRoute
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/admin/trips/$tripId/edit': typeof AdminTripsTripIdEditRoute
  '/api/admin/bookings/$bookingId': typeof ApiAdminBookingsBookingIdRoute
  '/api/admin/enquires/$enquiryId': typeof ApiAdminEnquiresEnquiryIdRoute
  '/api/admin/itinerary-submissions/$submissionId': typeof ApiAdminItinerarySubmissionsSubmissionIdRoute
  '/api/admin/meetups/$meetupId': typeof ApiAdminMeetupsMeetupIdRoute
  '/api/admin/meetups/images': typeof ApiAdminMeetupsImagesRoute
  '/api/admin/trips/$tripId': typeof ApiAdminTripsTripIdRoute
  '/api/trips/$tripId/images': typeof ApiTripsTripIdImagesRouteWithChildren
  '/api/trips/$tripId/itinerary': typeof ApiTripsTripIdItineraryRouteWithChildren
  '/api/trips/$tripId/images/$imageId': typeof ApiTripsTripIdImagesImageIdRoute
  '/api/trips/$tripId/itinerary/$itineraryId': typeof ApiTripsTripIdItineraryItineraryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/itinerary': typeof ItineraryRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trip-detail': typeof TripDetailRoute
  '/trips': typeof TripsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/itineraries': typeof AdminItinerariesRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/booking': typeof ApiBookingRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/api/itinerary-submissions': typeof ApiItinerarySubmissionsRoute
  '/api/meetups': typeof ApiMeetupsRoute
  '/api/my-bookings': typeof ApiMyBookingsRoute
  '/api/trips': typeof ApiTripsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/itinerary/submit': typeof ItinerarySubmitRoute
  '/admin': typeof AdminIndexRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRouteWithChildren
  '/api/admin/enquiries': typeof ApiAdminEnquiriesRoute
  '/api/admin/itinerary-submission-settings': typeof ApiAdminItinerarySubmissionSettingsRoute
  '/api/admin/itinerary-submissions': typeof ApiAdminItinerarySubmissionsRouteWithChildren
  '/api/admin/meetups': typeof ApiAdminMeetupsRouteWithChildren
  '/api/admin/trips': typeof ApiAdminTripsRouteWithChildren
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/trips/$tripId': typeof ApiTripsTripIdRouteWithChildren
  '/admin/meetups': typeof AdminMeetupsIndexRoute
  '/admin/trips': typeof AdminTripsIndexRoute
  '/admin/trips/$tripId/edit': typeof AdminTripsTripIdEditRoute
  '/api/admin/bookings/$bookingId': typeof ApiAdminBookingsBookingIdRoute
  '/api/admin/enquires/$enquiryId': typeof ApiAdminEnquiresEnquiryIdRoute
  '/api/admin/itinerary-submissions/$submissionId': typeof ApiAdminItinerarySubmissionsSubmissionIdRoute
  '/api/admin/meetups/$meetupId': typeof ApiAdminMeetupsMeetupIdRoute
  '/api/admin/meetups/images': typeof ApiAdminMeetupsImagesRoute
  '/api/admin/trips/$tripId': typeof ApiAdminTripsTripIdRoute
  '/api/trips/$tripId/images': typeof ApiTripsTripIdImagesRouteWithChildren
  '/api/trips/$tripId/itinerary': typeof ApiTripsTripIdItineraryRouteWithChildren
  '/api/trips/$tripId/images/$imageId': typeof ApiTripsTripIdImagesImageIdRoute
  '/api/trips/$tripId/itinerary/$itineraryId': typeof ApiTripsTripIdItineraryItineraryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/itinerary': typeof ItineraryRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trip-detail': typeof TripDetailRoute
  '/trips': typeof TripsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/itineraries': typeof AdminItinerariesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meetups': typeof AdminMeetupsRouteWithChildren
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/api/booking': typeof ApiBookingRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/api/itinerary-submissions': typeof ApiItinerarySubmissionsRoute
  '/api/meetups': typeof ApiMeetupsRoute
  '/api/my-bookings': typeof ApiMyBookingsRoute
  '/api/trips': typeof ApiTripsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/itinerary/submit': typeof ItinerarySubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRouteWithChildren
  '/api/admin/enquiries': typeof ApiAdminEnquiriesRoute
  '/api/admin/itinerary-submission-settings': typeof ApiAdminItinerarySubmissionSettingsRoute
  '/api/admin/itinerary-submissions': typeof ApiAdminItinerarySubmissionsRouteWithChildren
  '/api/admin/meetups': typeof ApiAdminMeetupsRouteWithChildren
  '/api/admin/trips': typeof ApiAdminTripsRouteWithChildren
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/trips/$tripId': typeof ApiTripsTripIdRouteWithChildren
  '/admin/meetups/': typeof AdminMeetupsIndexRoute
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/admin/trips/$tripId/edit': typeof AdminTripsTripIdEditRoute
  '/api/admin/bookings/$bookingId': typeof ApiAdminBookingsBookingIdRoute
  '/api/admin/enquires/$enquiryId': typeof ApiAdminEnquiresEnquiryIdRoute
  '/api/admin/itinerary-submissions/$submissionId': typeof ApiAdminItinerarySubmissionsSubmissionIdRoute
  '/api/admin/meetups/$meetupId': typeof ApiAdminMeetupsMeetupIdRoute
  '/api/admin/meetups/images': typeof ApiAdminMeetupsImagesRoute
  '/api/admin/trips/$tripId': typeof ApiAdminTripsTripIdRoute
  '/api/trips/$tripId/images': typeof ApiTripsTripIdImagesRouteWithChildren
  '/api/trips/$tripId/itinerary': typeof ApiTripsTripIdItineraryRouteWithChildren
  '/api/trips/$tripId/images/$imageId': typeof ApiTripsTripIdImagesImageIdRoute
  '/api/trips/$tripId/itinerary/$itineraryId': typeof ApiTripsTripIdItineraryItineraryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/itinerary'
    | '/login'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/trip-detail'
    | '/trips'
    | '/admin/bookings'
    | '/admin/itineraries'
    | '/admin/login'
    | '/admin/meetups'
    | '/admin/trips'
    | '/api/booking'
    | '/api/enquiries'
    | '/api/itinerary-submissions'
    | '/api/meetups'
    | '/api/my-bookings'
    | '/api/trips'
    | '/auth/callback'
    | '/dashboard/bookings'
    | '/itinerary/submit'
    | '/admin/'
    | '/admin/trips/new'
    | '/api/admin/bookings'
    | '/api/admin/enquiries'
    | '/api/admin/itinerary-submission-settings'
    | '/api/admin/itinerary-submissions'
    | '/api/admin/meetups'
    | '/api/admin/trips'
    | '/api/auth/me'
    | '/api/trips/$tripId'
    | '/admin/meetups/'
    | '/admin/trips/'
    | '/admin/trips/$tripId/edit'
    | '/api/admin/bookings/$bookingId'
    | '/api/admin/enquires/$enquiryId'
    | '/api/admin/itinerary-submissions/$submissionId'
    | '/api/admin/meetups/$meetupId'
    | '/api/admin/meetups/images'
    | '/api/admin/trips/$tripId'
    | '/api/trips/$tripId/images'
    | '/api/trips/$tripId/itinerary'
    | '/api/trips/$tripId/images/$imageId'
    | '/api/trips/$tripId/itinerary/$itineraryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/contact'
    | '/itinerary'
    | '/login'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/trip-detail'
    | '/trips'
    | '/admin/bookings'
    | '/admin/itineraries'
    | '/admin/login'
    | '/api/booking'
    | '/api/enquiries'
    | '/api/itinerary-submissions'
    | '/api/meetups'
    | '/api/my-bookings'
    | '/api/trips'
    | '/auth/callback'
    | '/dashboard/bookings'
    | '/itinerary/submit'
    | '/admin'
    | '/admin/trips/new'
    | '/api/admin/bookings'
    | '/api/admin/enquiries'
    | '/api/admin/itinerary-submission-settings'
    | '/api/admin/itinerary-submissions'
    | '/api/admin/meetups'
    | '/api/admin/trips'
    | '/api/auth/me'
    | '/api/trips/$tripId'
    | '/admin/meetups'
    | '/admin/trips'
    | '/admin/trips/$tripId/edit'
    | '/api/admin/bookings/$bookingId'
    | '/api/admin/enquires/$enquiryId'
    | '/api/admin/itinerary-submissions/$submissionId'
    | '/api/admin/meetups/$meetupId'
    | '/api/admin/meetups/images'
    | '/api/admin/trips/$tripId'
    | '/api/trips/$tripId/images'
    | '/api/trips/$tripId/itinerary'
    | '/api/trips/$tripId/images/$imageId'
    | '/api/trips/$tripId/itinerary/$itineraryId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/itinerary'
    | '/login'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/trip-detail'
    | '/trips'
    | '/admin/bookings'
    | '/admin/itineraries'
    | '/admin/login'
    | '/admin/meetups'
    | '/admin/trips'
    | '/api/booking'
    | '/api/enquiries'
    | '/api/itinerary-submissions'
    | '/api/meetups'
    | '/api/my-bookings'
    | '/api/trips'
    | '/auth/callback'
    | '/dashboard/bookings'
    | '/itinerary/submit'
    | '/admin/'
    | '/admin/trips/new'
    | '/api/admin/bookings'
    | '/api/admin/enquiries'
    | '/api/admin/itinerary-submission-settings'
    | '/api/admin/itinerary-submissions'
    | '/api/admin/meetups'
    | '/api/admin/trips'
    | '/api/auth/me'
    | '/api/trips/$tripId'
    | '/admin/meetups/'
    | '/admin/trips/'
    | '/admin/trips/$tripId/edit'
    | '/api/admin/bookings/$bookingId'
    | '/api/admin/enquires/$enquiryId'
    | '/api/admin/itinerary-submissions/$submissionId'
    | '/api/admin/meetups/$meetupId'
    | '/api/admin/meetups/images'
    | '/api/admin/trips/$tripId'
    | '/api/trips/$tripId/images'
    | '/api/trips/$tripId/itinerary'
    | '/api/trips/$tripId/images/$imageId'
    | '/api/trips/$tripId/itinerary/$itineraryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  ItineraryRoute: typeof ItineraryRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TripDetailRoute: typeof TripDetailRoute
  TripsRoute: typeof TripsRoute
  ApiBookingRoute: typeof ApiBookingRoute
  ApiEnquiriesRoute: typeof ApiEnquiriesRoute
  ApiItinerarySubmissionsRoute: typeof ApiItinerarySubmissionsRoute
  ApiMeetupsRoute: typeof ApiMeetupsRoute
  ApiMyBookingsRoute: typeof ApiMyBookingsRoute
  ApiTripsRoute: typeof ApiTripsRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  ApiAdminBookingsRoute: typeof ApiAdminBookingsRouteWithChildren
  ApiAdminEnquiriesRoute: typeof ApiAdminEnquiriesRoute
  ApiAdminItinerarySubmissionSettingsRoute: typeof ApiAdminItinerarySubmissionSettingsRoute
  ApiAdminItinerarySubmissionsRoute: typeof ApiAdminItinerarySubmissionsRouteWithChildren
  ApiAdminMeetupsRoute: typeof ApiAdminMeetupsRouteWithChildren
  ApiAdminTripsRoute: typeof ApiAdminTripsRouteWithChildren
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAdminEnquiresEnquiryIdRoute: typeof ApiAdminEnquiresEnquiryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-detail': {
      id: '/trip-detail'
      path: '/trip-detail'
      fullPath: '/trip-detail'
      preLoaderRoute: typeof TripDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/itineraries': {
      id: '/admin/itineraries'
      path: '/itineraries'
      fullPath: '/admin/itineraries'
      preLoaderRoute: typeof AdminItinerariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meetups': {
      id: '/admin/meetups'
      path: '/meetups'
      fullPath: '/admin/meetups'
      preLoaderRoute: typeof AdminMeetupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/booking': {
      id: '/api/booking'
      path: '/api/booking'
      fullPath: '/api/booking'
      preLoaderRoute: typeof ApiBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enquiries': {
      id: '/api/enquiries'
      path: '/api/enquiries'
      fullPath: '/api/enquiries'
      preLoaderRoute: typeof ApiEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/itinerary-submissions': {
      id: '/api/itinerary-submissions'
      path: '/api/itinerary-submissions'
      fullPath: '/api/itinerary-submissions'
      preLoaderRoute: typeof ApiItinerarySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetups': {
      id: '/api/meetups'
      path: '/api/meetups'
      fullPath: '/api/meetups'
      preLoaderRoute: typeof ApiMeetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my-bookings': {
      id: '/api/my-bookings'
      path: '/api/my-bookings'
      fullPath: '/api/my-bookings'
      preLoaderRoute: typeof ApiMyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trips': {
      id: '/api/trips'
      path: '/api/trips'
      fullPath: '/api/trips'
      preLoaderRoute: typeof ApiTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/submit': {
      id: '/itinerary/submit'
      path: '/submit'
      fullPath: '/itinerary/submit'
      preLoaderRoute: typeof ItinerarySubmitRouteImport
      parentRoute: typeof ItineraryRoute
    }
    '/admin/meetups/': {
      id: '/admin/meetups/'
      path: '/'
      fullPath: '/admin/meetups/'
      preLoaderRoute: typeof AdminMeetupsIndexRouteImport
      parentRoute: typeof AdminMeetupsRoute
    }
    '/admin/trips/': {
      id: '/admin/trips/'
      path: '/'
      fullPath: '/admin/trips/'
      preLoaderRoute: typeof AdminTripsIndexRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/admin/trips/new': {
      id: '/admin/trips/new'
      path: '/new'
      fullPath: '/admin/trips/new'
      preLoaderRoute: typeof AdminTripsNewRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/api/admin/bookings': {
      id: '/api/admin/bookings'
      path: '/api/admin/bookings'
      fullPath: '/api/admin/bookings'
      preLoaderRoute: typeof ApiAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/enquiries': {
      id: '/api/admin/enquiries'
      path: '/api/admin/enquiries'
      fullPath: '/api/admin/enquiries'
      preLoaderRoute: typeof ApiAdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/itinerary-submission-settings': {
      id: '/api/admin/itinerary-submission-settings'
      path: '/api/admin/itinerary-submission-settings'
      fullPath: '/api/admin/itinerary-submission-settings'
      preLoaderRoute: typeof ApiAdminItinerarySubmissionSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/itinerary-submissions': {
      id: '/api/admin/itinerary-submissions'
      path: '/api/admin/itinerary-submissions'
      fullPath: '/api/admin/itinerary-submissions'
      preLoaderRoute: typeof ApiAdminItinerarySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/meetups': {
      id: '/api/admin/meetups'
      path: '/api/admin/meetups'
      fullPath: '/api/admin/meetups'
      preLoaderRoute: typeof ApiAdminMeetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/trips': {
      id: '/api/admin/trips'
      path: '/api/admin/trips'
      fullPath: '/api/admin/trips'
      preLoaderRoute: typeof ApiAdminTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trips/$tripId': {
      id: '/api/trips/$tripId'
      path: '/$tripId'
      fullPath: '/api/trips/$tripId'
      preLoaderRoute: typeof ApiTripsTripIdRouteImport
      parentRoute: typeof ApiTripsRoute
    }
    '/admin/trips/$tripId/edit': {
      id: '/admin/trips/$tripId/edit'
      path: '/$tripId/edit'
      fullPath: '/admin/trips/$tripId/edit'
      preLoaderRoute: typeof AdminTripsTripIdEditRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/api/admin/bookings/$bookingId': {
      id: '/api/admin/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/api/admin/bookings/$bookingId'
      preLoaderRoute: typeof ApiAdminBookingsBookingIdRouteImport
      parentRoute: typeof ApiAdminBookingsRoute
    }
    '/api/admin/enquires/$enquiryId': {
      id: '/api/admin/enquires/$enquiryId'
      path: '/api/admin/enquires/$enquiryId'
      fullPath: '/api/admin/enquires/$enquiryId'
      preLoaderRoute: typeof ApiAdminEnquiresEnquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/itinerary-submissions/$submissionId': {
      id: '/api/admin/itinerary-submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/api/admin/itinerary-submissions/$submissionId'
      preLoaderRoute: typeof ApiAdminItinerarySubmissionsSubmissionIdRouteImport
      parentRoute: typeof ApiAdminItinerarySubmissionsRoute
    }
    '/api/admin/meetups/$meetupId': {
      id: '/api/admin/meetups/$meetupId'
      path: '/$meetupId'
      fullPath: '/api/admin/meetups/$meetupId'
      preLoaderRoute: typeof ApiAdminMeetupsMeetupIdRouteImport
      parentRoute: typeof ApiAdminMeetupsRoute
    }
    '/api/admin/meetups/images': {
      id: '/api/admin/meetups/images'
      path: '/images'
      fullPath: '/api/admin/meetups/images'
      preLoaderRoute: typeof ApiAdminMeetupsImagesRouteImport
      parentRoute: typeof ApiAdminMeetupsRoute
    }
    '/api/admin/trips/$tripId': {
      id: '/api/admin/trips/$tripId'
      path: '/$tripId'
      fullPath: '/api/admin/trips/$tripId'
      preLoaderRoute: typeof ApiAdminTripsTripIdRouteImport
      parentRoute: typeof ApiAdminTripsRoute
    }
    '/api/trips/$tripId/images': {
      id: '/api/trips/$tripId/images'
      path: '/images'
      fullPath: '/api/trips/$tripId/images'
      preLoaderRoute: typeof ApiTripsTripIdImagesRouteImport
      parentRoute: typeof ApiTripsTripIdRoute
    }
    '/api/trips/$tripId/itinerary': {
      id: '/api/trips/$tripId/itinerary'
      path: '/itinerary'
      fullPath: '/api/trips/$tripId/itinerary'
      preLoaderRoute: typeof ApiTripsTripIdItineraryRouteImport
      parentRoute: typeof ApiTripsTripIdRoute
    }
    '/api/trips/$tripId/images/$imageId': {
      id: '/api/trips/$tripId/images/$imageId'
      path: '/$imageId'
      fullPath: '/api/trips/$tripId/images/$imageId'
      preLoaderRoute: typeof ApiTripsTripIdImagesImageIdRouteImport
      parentRoute: typeof ApiTripsTripIdImagesRoute
    }
    '/api/trips/$tripId/itinerary/$itineraryId': {
      id: '/api/trips/$tripId/itinerary/$itineraryId'
      path: '/$itineraryId'
      fullPath: '/api/trips/$tripId/itinerary/$itineraryId'
      preLoaderRoute: typeof ApiTripsTripIdItineraryItineraryIdRouteImport
      parentRoute: typeof ApiTripsTripIdItineraryRoute
    }
  }
}

interface AdminMeetupsRouteChildren {
  AdminMeetupsIndexRoute: typeof AdminMeetupsIndexRoute
}

const AdminMeetupsRouteChildren: AdminMeetupsRouteChildren = {
  AdminMeetupsIndexRoute: AdminMeetupsIndexRoute,
}

const AdminMeetupsRouteWithChildren = AdminMeetupsRoute._addFileChildren(
  AdminMeetupsRouteChildren,
)

interface AdminTripsRouteChildren {
  AdminTripsNewRoute: typeof AdminTripsNewRoute
  AdminTripsIndexRoute: typeof AdminTripsIndexRoute
  AdminTripsTripIdEditRoute: typeof AdminTripsTripIdEditRoute
}

const AdminTripsRouteChildren: AdminTripsRouteChildren = {
  AdminTripsNewRoute: AdminTripsNewRoute,
  AdminTripsIndexRoute: AdminTripsIndexRoute,
  AdminTripsTripIdEditRoute: AdminTripsTripIdEditRoute,
}

const AdminTripsRouteWithChildren = AdminTripsRoute._addFileChildren(
  AdminTripsRouteChildren,
)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminItinerariesRoute: typeof AdminItinerariesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMeetupsRoute: typeof AdminMeetupsRouteWithChildren
  AdminTripsRoute: typeof AdminTripsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminItinerariesRoute: AdminItinerariesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMeetupsRoute: AdminMeetupsRouteWithChildren,
  AdminTripsRoute: AdminTripsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ItineraryRouteChildren {
  ItinerarySubmitRoute: typeof ItinerarySubmitRoute
}

const ItineraryRouteChildren: ItineraryRouteChildren = {
  ItinerarySubmitRoute: ItinerarySubmitRoute,
}

const ItineraryRouteWithChildren = ItineraryRoute._addFileChildren(
  ItineraryRouteChildren,
)

interface ApiTripsTripIdImagesRouteChildren {
  ApiTripsTripIdImagesImageIdRoute: typeof ApiTripsTripIdImagesImageIdRoute
}

const ApiTripsTripIdImagesRouteChildren: ApiTripsTripIdImagesRouteChildren = {
  ApiTripsTripIdImagesImageIdRoute: ApiTripsTripIdImagesImageIdRoute,
}

const ApiTripsTripIdImagesRouteWithChildren =
  ApiTripsTripIdImagesRoute._addFileChildren(ApiTripsTripIdImagesRouteChildren)

interface ApiTripsTripIdItineraryRouteChildren {
  ApiTripsTripIdItineraryItineraryIdRoute: typeof ApiTripsTripIdItineraryItineraryIdRoute
}

const ApiTripsTripIdItineraryRouteChildren: ApiTripsTripIdItineraryRouteChildren =
  {
    ApiTripsTripIdItineraryItineraryIdRoute:
      ApiTripsTripIdItineraryItineraryIdRoute,
  }

const ApiTripsTripIdItineraryRouteWithChildren =
  ApiTripsTripIdItineraryRoute._addFileChildren(
    ApiTripsTripIdItineraryRouteChildren,
  )

interface ApiTripsTripIdRouteChildren {
  ApiTripsTripIdImagesRoute: typeof ApiTripsTripIdImagesRouteWithChildren
  ApiTripsTripIdItineraryRoute: typeof ApiTripsTripIdItineraryRouteWithChildren
}

const ApiTripsTripIdRouteChildren: ApiTripsTripIdRouteChildren = {
  ApiTripsTripIdImagesRoute: ApiTripsTripIdImagesRouteWithChildren,
  ApiTripsTripIdItineraryRoute: ApiTripsTripIdItineraryRouteWithChildren,
}

const ApiTripsTripIdRouteWithChildren = ApiTripsTripIdRoute._addFileChildren(
  ApiTripsTripIdRouteChildren,
)

interface ApiTripsRouteChildren {
  ApiTripsTripIdRoute: typeof ApiTripsTripIdRouteWithChildren
}

const ApiTripsRouteChildren: ApiTripsRouteChildren = {
  ApiTripsTripIdRoute: ApiTripsTripIdRouteWithChildren,
}

const ApiTripsRouteWithChildren = ApiTripsRoute._addFileChildren(
  ApiTripsRouteChildren,
)

interface ApiAdminBookingsRouteChildren {
  ApiAdminBookingsBookingIdRoute: typeof ApiAdminBookingsBookingIdRoute
}

const ApiAdminBookingsRouteChildren: ApiAdminBookingsRouteChildren = {
  ApiAdminBookingsBookingIdRoute: ApiAdminBookingsBookingIdRoute,
}

const ApiAdminBookingsRouteWithChildren =
  ApiAdminBookingsRoute._addFileChildren(ApiAdminBookingsRouteChildren)

interface ApiAdminItinerarySubmissionsRouteChildren {
  ApiAdminItinerarySubmissionsSubmissionIdRoute: typeof ApiAdminItinerarySubmissionsSubmissionIdRoute
}

const ApiAdminItinerarySubmissionsRouteChildren: ApiAdminItinerarySubmissionsRouteChildren =
  {
    ApiAdminItinerarySubmissionsSubmissionIdRoute:
      ApiAdminItinerarySubmissionsSubmissionIdRoute,
  }

const ApiAdminItinerarySubmissionsRouteWithChildren =
  ApiAdminItinerarySubmissionsRoute._addFileChildren(
    ApiAdminItinerarySubmissionsRouteChildren,
  )

interface ApiAdminMeetupsRouteChildren {
  ApiAdminMeetupsMeetupIdRoute: typeof ApiAdminMeetupsMeetupIdRoute
  ApiAdminMeetupsImagesRoute: typeof ApiAdminMeetupsImagesRoute
}

const ApiAdminMeetupsRouteChildren: ApiAdminMeetupsRouteChildren = {
  ApiAdminMeetupsMeetupIdRoute: ApiAdminMeetupsMeetupIdRoute,
  ApiAdminMeetupsImagesRoute: ApiAdminMeetupsImagesRoute,
}

const ApiAdminMeetupsRouteWithChildren = ApiAdminMeetupsRoute._addFileChildren(
  ApiAdminMeetupsRouteChildren,
)

interface ApiAdminTripsRouteChildren {
  ApiAdminTripsTripIdRoute: typeof ApiAdminTripsTripIdRoute
}

const ApiAdminTripsRouteChildren: ApiAdminTripsRouteChildren = {
  ApiAdminTripsTripIdRoute: ApiAdminTripsTripIdRoute,
}

const ApiAdminTripsRouteWithChildren = ApiAdminTripsRoute._addFileChildren(
  ApiAdminTripsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  ItineraryRoute: ItineraryRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TripDetailRoute: TripDetailRoute,
  TripsRoute: TripsRoute,
  ApiBookingRoute: ApiBookingRoute,
  ApiEnquiriesRoute: ApiEnquiriesRoute,
  ApiItinerarySubmissionsRoute: ApiItinerarySubmissionsRoute,
  ApiMeetupsRoute: ApiMeetupsRoute,
  ApiMyBookingsRoute: ApiMyBookingsRoute,
  ApiTripsRoute: ApiTripsRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  ApiAdminBookingsRoute: ApiAdminBookingsRouteWithChildren,
  ApiAdminEnquiriesRoute: ApiAdminEnquiriesRoute,
  ApiAdminItinerarySubmissionSettingsRoute:
    ApiAdminItinerarySubmissionSettingsRoute,
  ApiAdminItinerarySubmissionsRoute:
    ApiAdminItinerarySubmissionsRouteWithChildren,
  ApiAdminMeetupsRoute: ApiAdminMeetupsRouteWithChildren,
  ApiAdminTripsRoute: ApiAdminTripsRouteWithChildren,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAdminEnquiresEnquiryIdRoute: ApiAdminEnquiresEnquiryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
